("LFACTORY.DGO"
 ("factory-h.o"
  "ffight-projectile.o"
  "ftank-projectile.o"
  "fturret-projectile.o"
  ;; warf-projectile.o et h-warf.o sont dans GAME (jak 3 en ligne : Hellcat partout)
  "fac-gunturret.o"
  "fac-robotank-h.o"
  "fac-robotank-turret.o"
  "fac-robotank.o"
  "fac-tower.o"
  "factory-manager.o"
  "factory-hud.o"
  "factorya-init.o"
  "lfactory.go"
 ))
